function cpCan(varargin)
% 
% DialogBox pour ajouter des canaux, en copiant ceux existants
%
% Lorsque l'on copie des canaux, on a le choix de copier les 
% datas et les paramètres reliés aux canaux, ou bien seulement
% copier les paramètres en laissant les datas vides.
%
% Si on choisit de ne pas copier les paramètres, par défaut il
% copiera les paramètres du premier canal.
%
  if nargin == 0
    commande = 'ouverture';
  else
    commande = varargin{1};
  end
  hA =CAnalyse.getInstance();
  hF =hA.findcurfich();
  hdchnl =hF.Hdchnl;
  vg =hF.Vg;
  %--------------
  switch commande
  %---------------
  case 'ouverture'
    if vg.nad>2;letop=vg.nad;else;letop=vg.nad+1;end
    larg =350;
    haut =370;
    lapos =positionfen('G','H', larg, haut, gcf);
    lafig = figure('Name','AJOUTER-CANAUX', 'tag','ICopieCanal', ...
          'Position',lapos, ...
          'CloseRequestFcn','cpCan(''fermer'')',...
          'DefaultUIControlBackgroundColor',[0.8 0.8 0.8],...
          'DefaultUIControlunits','pixels',...
          'DefaultUIControlFontSize',9,...
          'DefaultUIControlStyle','checkbox', ...
          'DefaultUIControlHorizontalAlignment','left',...
          'Resize', 'off');															%
    uicontrol('Parent',lafig, ...
          'FontSize',16,...
          'Position',[30 325 290 25], ...
          'String','Création de nouveaux canaux', ...
          'Style','text');
    uicontrol('Parent',lafig, 'tag','CCChoixCanal', ...
          'BackgroundColor',[1 1 1], ...
          'Min',1,...
          'Max',letop,...
          'Position',[75 125 200 175], ...
          'String',hdchnl.Listadname, ...
          'Style','listbox', ...
          'Value',1);
    uicontrol('Parent',lafig, 'tag','CCNombreDeCopie', ...
          'BackgroundColor',[1 1 1], ...
          'Position',[250 75 35 25], ...
          'Style','edit', ...
          'String','1');
    uicontrol('Parent',lafig, ...
          'Position',[75 75 175 20], ...
          'FontSize',10,...
          'Style','text',...
          'String','Nombre de copie à créer');
    uicontrol('Parent',lafig, ...
          'Callback','cpCan(''ajoute'')', ...
          'Position',[120 25 100 25], ...
          'style','PushButton',...
          'String','Création');
    set(lafig,'WindowStyle','modal');

  %------------
  case 'ajoute'
    lescan =get(findobj('tag','CCChoixCanal'),'Value')';
    nbdecop =str2num(get(findobj('tag','CCNombreDeCopie'),'String'));
    nbdecan =length(lescan);
    hwb =waitbar(0, 'Copie');
    letot =nbdecop*nbdecan;
    indx =1;
    while nbdecop
      hdchnl.duplic(lescan);
      for U =1:nbdecan
        hF.CopieCanal(lescan(U), vg.nad+U);
        waitbar(indx/letot, hwb, ['Copie: ' num2str(indx)]);
        indx =indx+1;
      end
      vg.nad =vg.nad+nbdecan;
      nbdecop =nbdecop-1;
    end
    delete(hwb);
    vg.sauve =true;
    lafig =findobj('tag','ICopieCanal');
    delete(lafig);
    editCan;

  %------------
  case 'fermer'
    lafig =findobj('tag','ICopieCanal');
    delete(lafig);
    figure(hA.OFig.fig);
  %--
  end
end
