function editCan(varargin)
% 
% DialogBox pour éditer le nom des canaux.
%
% On peut aussi regénérer le commentaire qui apparaît dans
% la barre de status au bas de l'écran d'analyse, en cliquant
% sur le bouton "Effacer les commentaires pour ce canal".
%
  if nargin == 0
    commande = 'ouverture';
  else
    commande = varargin{1};
    edi = guidata(gcf);
  end
  hA =CAnalyse.getInstance();
  hF =hA.findcurfich();
  hdchnl =hF.Hdchnl;
  vg =hF.Vg;
  %
  switch(commande)
  %---------------
  case 'ouverture'
    edi.can=1;
    edi.nom=0;
    edi.freq=0;
    larg =450;
    haut =325;
    lapos =positionfen('G','H', larg, haut, gcf);
    edi.fig(1) = figure('Name','GESTION DES CANAUX', 'Position',lapos, ...
            'CloseRequestFcn','editCan(''fermer'')',...
            'DefaultUIControlBackgroundColor',[0.8 0.8 0.8],...
            'DefaultUIControlunits','pixels',...
            'DefaultUIControlFontSize',9,...
            'DefaultUIControlStyle','checkbox', ...
            'DefaultUIControlHorizontalAlignment','left',...
            'Resize', 'off');
    uicontrol('Parent',edi.fig(1), 'FontSize',16, 'Position',[25 295 350 25], ...
            'String','Choix des noms à modifier', 'Style','text');
    uicontrol('Parent',edi.fig(1), 'tag','ECChoixCanal', 'BackgroundColor',[1 1 1], ...
            'Position',[25 25 200 250], 'String',hdchnl.Listadname, ...
            'Callback','editCan(''ChangeCanal'')', 'Style','listbox', 'max',1, 'Value',1);
    tmp =hdchnl.adname{1};
    uicontrol('Parent',edi.fig(1), 'tag','ECNomCanal', ...
            'BackgroundColor',[1 1 1], ...
            'Position',[235 250 190 25], ...
            'Callback','editCan(''Ncanal'')',...
            'Style','edit', ...
            'String',tmp);
    uicontrol('Parent',edi.fig(1), ...
            'Position',[235 230 190 20], ...
            'FontSize',9,...
            'Style','text',...
            'String','Nom du canal');
    uicontrol('Parent',edi.fig(1), 'tag','ECFreqCanal', ...
            'BackgroundColor',[1 1 1], ...
            'Position',[235 190 50 25], ...
            'Callback','editCan(''Fcanal'')',...
            'Style','edit', ...
            'String',num2str(hdchnl.rate(1,1)));
    uicontrol('Parent',edi.fig(1), ...
            'Position',[290 190 135 20], ...
            'FontSize',9,...
            'Style','text',...
            'String','Fréquence d''acquisition');
    uicontrol('Parent',edi.fig(1), ...
            'BackgroundColor',[.9 .9 .9], ...
            'Position',[235 125 23 25], ...
            'style','PushButton',...
            'Callback','editCan(''comment'')');
    uicontrol('Parent',edi.fig(1), ...
            'HorizontalAlignment','Left', ...
            'Position',[265 120 160 30], ...
            'Style','text',...
            'String','Effacer les commentaires pour ce canal');
    uicontrol('Parent',edi.fig(1), ...
            'BackgroundColor',[.9 .9 .9], ...
            'Position',[280 25 100 25], ...
            'style','PushButton',...
            'string','Appliquer',...
            'Callback','editCan(''applique'')');
    set(edi.fig(1),'WindowStyle','modal');
    guidata(gcf,edi);
  %-----------------
  case 'ChangeCanal'
    edi.can =get(findobj('tag','ECChoixCanal'),'Value');
    edi.nom =0;
    edi.freq =0;
    tmp =hdchnl.adname{edi.can};
    set(findobj('tag','ECNomCanal'),'String',tmp);
    set(findobj('tag','ECFreqCanal'),'String',num2str(hdchnl.rate(edi.can,1)));
    guidata(gcf,edi);
  %------------
  case 'Ncanal'
    edi.nom =1;
    guidata(gcf,edi);
  %-----------
  case 'Fcanal'
    edi.freq =1;
    guidata(gcf,edi);
  %-------------
  case 'comment'
    edi.can =get(findobj('tag','ECChoixCanal'),'Value')';  %'
    tmp =[deblank(hdchnl.adname{edi.can}),'://'];
    for jj =1:vg.ess
      hdchnl.comment{edi.can, jj} =tmp;
    end
    vg.sauve =1;
  %--------------
  case 'applique'
    if edi.freq
      lafreq =str2num(get(findobj('tag','ECFreqCanal'),'String'));
      if isempty(lafreq)
        set(findobj('tag','ECFreqCanal'),'String',num2str(hdchnl.rate(edi.can,1)));
      else
        hdchnl.rate(edi.can,:) =lafreq;
        hdchnl.sweeptime(edi.can,:) =hdchnl.nsmpls(edi.can,:)/lafreq;
      end
    end
    if edi.nom
      lenom =deblank(get(findobj('tag','ECNomCanal'),'String'));
      hdchnl.adname{edi.can} =lenom;
      hdchnl.ResetListAdname();
      set(findobj('tag','ECChoixCanal'),'String',hdchnl.Listadname);
      vg.sauve =1;
    end
  %------------
  case 'fermer'
    delete(edi.fig(1));
    gaglobal('editnom');
  %--
  end
end
