%
% DialogBox pour demander les infos relatives à la différenciation
% puis on passe à l'action.
% En entrée:         Ppa  --> objet de la classe CDiffer(Bat)
%             Listadname  --> liste des noms de canaux
%-----------------------------------------------------------------
function GUIDiffer(Ppa, Listadname)
    letop =max(2,length(Listadname));
    BLANC =[1 1 1];
    lapos =positionfen('G','C',300,450);
    lafig =figure('Name','MENUDIFFER', 'Position',lapos, ...
            'CloseRequestFcn',@onFerme,...
            'DefaultUIControlBackgroundColor',[0.8 0.8 0.8],...
            'defaultUIControlunits','pixels',...
            'defaultUIControlFontSize',10,...
            'Resize','off');
    Ppa.fig =lafig;
    uicontrol('Parent',lafig, 'FontSize',12, 'Position',[25 400 250 25], ...
            'String','Choix des canal/aux à différencier', 'Style','text');
    uicontrol('Parent',lafig, 'tag','ListeCan', 'BackgroundColor',BLANC, ...
            'Position',[50 175 200 225], 'String',Listadname, ...
            'Min',1, 'Max',letop, 'Style','listbox', 'Value',1);
    uicontrol('Parent',lafig, 'tag','memeCan', 'Position',[25 140 250 25], ...
              'HorizontalAlignment','left', 'Style','checkbox', 'Value',0, ...
              'String','Placer le résultat dans le même canal');
    uicontrol('Parent',lafig, 'Position',[25 80 225 40], 'Style','text',...
              'String','Nombre de points pour le lissage (Largeur de fenêtre)');
    uicontrol('Parent',lafig, 'Style','edit', 'Tag','LargeurFenLissage', ...
              'BackgroundColor',BLANC, 'Position',[250 100 35 20], ...
              'Style','edit', 'String','11', ...
              'TooltipString','Si laissé à 0 ou 1, dérivé brute: (Xi+1)-(Xi)');
    uicontrol('Parent',lafig, 'Callback',@Ppa.travail, 'Position',[45 25 100 25], ...
              'String','Au travail!','tag','boutonTravail');
    set(lafig,'WindowStyle','modal');
end

function onFerme(varargin)
  delete(gcf);
end
