%
% Fabrication du GUI pour l'édition des niveaux/catégories
%
function GUIEditCateg(Ppa)
  try
    vg =Ppa.hF.Vg;
    catego =Ppa.hF.Catego;
    % on fabrique la liste d'essais libres
    lessai =catego.BatirListeEssaiLibre(vg.defniv);
    % on fabrique la liste d'essais assignées
    lessaib =catego.BatirListeEssaiAssocie(vg.defniv,1);
    largeur =500;
    hauteur =500;
    margeg =30;
    haut =25;
    lapos =positionfen('G','H', largeur, hauteur, gcf);
    hfig = figure('Name','CATÉGORIE', 'visible','on', 'Position',lapos, ...
            'CloseRequestFcn',{@quienllama,'Terminus'},...
            'DefaultUIControlBackgroundColor',[0.8 0.8 0.8],...
            'DefaultUIControlunits','pixels',...
            'DefaultUIControlFontSize',10,...
            'DefaultUIControlStyle','checkbox', ...
            'DefaultUIControlHorizontalAlignment','left',...
            'Resize', 'off');
    Ppa.hFig =hfig;
    posy=hauteur-30;
    uicontrol('Parent',hfig,'FontSize',15,'HorizontalAlignment','center',...
            'Position',[margeg posy (largeur-(2*margeg)) haut], ...
            'String','Édition des catégories','Style','text');
    posy=posy-50;
    Xmargeg=floor(largeur*0.1);
    largfen=floor(largeur*0.65);
    uicontrol('Parent',hfig, ...
            'Position',[Xmargeg posy largfen haut], ...
            'String','Nom du niveau puis cliquez Ajouter pour le créer', ...
            'Style','text');
    posy=posy-20;
    Xmargeg=floor(largeur*0.1);
    largfen=floor(largeur*0.6);
    uicontrol('Parent',hfig, 'tag','ECNouveauNiveau', ...
            'HorizontalAlignment','left',...
            'BackgroundColor',[1 1 1], ...
            'Position',[Xmargeg posy largfen haut], ...
            'callback',{@quienllama,'AjouterNiveau'}, ...
            'Style','edit', ...
            'String','');
    Xmargeg=floor(largeur*0.7);
    largfen=floor(largeur*0.15);
    uicontrol('Parent',hfig, ...
            'callback',{@quienllama,'AjouterNiveau'}, ...
            'Position',[Xmargeg posy largfen haut], ...
            'Style','pushbutton',...
            'String','Ajouter');                         % NOUVEAU NIVEAU
    posy=posy-30;
    Xmargeg=floor(largeur*0.1);
    largfen=floor(largeur*0.65);
    uicontrol('Parent',hfig, ...
            'Position',[Xmargeg posy largfen haut], ...
            'String','Nom de la catégorie puis cliquez Ajouter pour la créer', ...
            'Style','text');
    posy=posy-20;
    Xmargeg=floor(largeur*0.1);
    largfen=floor(largeur*0.6);
    uicontrol('Parent',hfig, 'tag','ECNouvelCategorie', ...
            'HorizontalAlignment','left',...
            'BackgroundColor',[1 1 1], ...
            'Position',[Xmargeg posy largfen haut], ...
            'callback',{@quienllama,'AjouterCategorie'}, ...
            'Style','edit', ...
            'String','');
    Xmargeg=floor(largeur*0.7);
    largfen=floor(largeur*0.15);
    uicontrol('Parent',hfig, ...
            'callback',{@quienllama,'AjouterCategorie'}, ...
            'Position',[Xmargeg posy largfen haut], ...
            'Style','pushbutton',...
            'String','Ajouter');                           % Nouvelle CAT
    posy=posy-2*haut;
    Xmargeg=floor(largeur*0.1);
    largfen=floor(largeur*0.6);
    listniv ={};
    if vg.niveau
      for i=1:vg.niveau
        listniv{end+1}=catego.Dato(1,i,1).nom;
      end
    end
    if isempty(listniv)
      listniv ='.';
    end
    uicontrol('Parent',hfig, 'tag','ECListeNiveau', ...
            'callback',{@quienllama,'ChangeNiveau'}, ...
            'String',listniv,...
            'Style','popupmenu', ...
            'Value',vg.defniv,...
            'Position',[Xmargeg posy largfen haut]);       % Change de niveau
    Xmargeg=floor(largeur*0.7);
    largfen=floor(largeur*0.10);
    uicontrol('Parent',hfig, ...
            'callback',{@quienllama,'EnleverNiveau'}, ...
            'Position',[Xmargeg posy largfen haut], ...
            'Style','pushbutton',...
            'String','Suppr');
    Xmargeg=floor(largeur*0.81);
    uicontrol('Parent',hfig, ...
            'callback',{@quienllama,'ModifieNiveau'}, ...
            'Position',[Xmargeg posy largfen haut], ...
            'Style','pushbutton',...
            'String','Modif');
    posy=floor(posy-1.5*haut);
    Xmargeg=floor(largeur*0.1);
    largfen=floor(largeur*0.6);
    listcat ={};
    if (vg.niveau > 0) && (catego.Dato(1,vg.defniv,1).ncat > 0)
      for i=1:catego.Dato(1,vg.defniv,1).ncat
        listcat{end+1} =catego.Dato(2,vg.defniv,i).nom;
      end
    end
    if isempty(listcat)
      listcat='.';
    end
    uicontrol('Parent',hfig, 'tag','ECListeCategorie', ...
            'callback',{@quienllama,'ChangeCategorie'}, ...
            'Style','popupmenu', ...
            'Value',1,...
            'String',listcat,...
            'Position',[Xmargeg posy largfen haut]);       % Change de catégorie
    Xmargeg=floor(largeur*0.7);
    largfen=floor(largeur*0.10);
    uicontrol('Parent',hfig, ...
            'callback',{@quienllama,'EnleverCategorie'}, ...
            'Position',[Xmargeg posy largfen haut], ...
            'Style','pushbutton',...
            'String','Suppr');
    Xmargeg=floor(largeur*0.81);
    uicontrol('Parent',hfig, ...
            'callback',{@quienllama,'ModifieCategorie'}, ...
            'Position',[Xmargeg posy largfen haut], ...
            'Style','pushbutton',...
            'String','Modif');
    Xmargeg=floor(largeur*0.1);
    largfen=floor(largeur*0.25);
    inposy=posy-20;
    hfen=150;
    posy=inposy-hfen;
    if vg.ess>2;letopess=vg.ess;else;letopess=vg.ess+1;end
    uicontrol('Parent',hfig, 'tag','ECEssaiDisponible', ...
            'BackgroundColor',[1 1 1], ...
            'Position',[Xmargeg posy largfen hfen], ...
            'String',lessai, ...
            'Max',letopess,...
            'Style','listbox');                         % Essais disponibles
    Xmargeg=floor(largeur*0.65);
    largfen=floor(largeur*0.25);
    uicontrol('Parent',hfig, 'tag','ECEssaiAttribue', ...
            'BackgroundColor',[1 1 1], ...
            'Position',[Xmargeg posy largfen hfen], ...
            'String',lessaib, ...
            'Max',letopess,...
            'Style','listbox');                         % Essais de la catégorie
    posy=inposy-3*haut;
    largfen=floor(largeur*0.25);
    Xmargeg=floor(largeur*0.375);
    uicontrol('Parent',hfig, ...
            'callback',{@quienllama,'AjouterEssai'}, ...
            'Position',[Xmargeg posy largfen haut], ...
            'Style','pushbutton',...
            'String',' Ajouter essai --> ');
    posy=posy-2*haut;
    largfen=floor(largeur*0.25);
    Xmargeg=floor(largeur*0.375);
    uicontrol('Parent',hfig, ...
            'callback',{@quienllama,'EnleverEssai'}, ...
            'Position',[Xmargeg posy largfen haut], ...
            'Style','pushbutton',...
            'String',' <-- Soustraire essai ');
    posy=posy-4*haut;
    largfen=floor(largeur*0.5);
    Xmargeg=floor(largeur*0.1);
    uicontrol('Parent',hfig,'tag','ECNiveauDefaut','callback',{@quienllama,'DefaultNiveau'},...
              'Max',1,'Position',[Xmargeg posy largfen haut], ...
              'TooltipString','Niveau par défaut','Style','popupmenu',...
              'String',listniv,'Value', vg.defniv);
    setappdata(hfig,'Ppa',Ppa);
    set(hfig,'WindowStyle','modal');

  catch sss;
    disp(sss.message)
    for U=1:length(sss.stack)
      disp(sss.stack(U))
    end
    set(hfig,'WindowStyle','normal');
  end

end

%-----------------------------------------
% Callback des différents uicontrol du GUI
% on call la method "Ppa.(autre)"
%-----------------------------------------
function quienllama(src,evt, autre)
  Ppa =getappdata(gcf,'Ppa');
  Ppa.(autre)(src);
end
