%
% fonction pour demander les infos afin d'importer un fichier texte
% MEK, mai 2011
%
function GUILirTexte(Ppa)
  large =625;                                 % largeur fenêtre totale
  largreel =800;                              % largeur fenêtre totale
  haut  =385;                                 % hauteur fenêtre totale
  epais =25;                                  % épaisseur normale d'un objet
  ptitepais =15;                              % épaisseur pour écriture avec font 6
  bordure =20;                                % bordure de la deuxième colonne
  lebord1 =25;                                % marge colonne de gauche
  lebord2 =round(large/2) + bordure;          % marge colonne de droite
  lebord3 =large+bordure;
  bouton =20;                                 % largeur d'un bouton
  largfen =50;                                % largeur fenêtre input texte
  fenetre =[largfen epais];                   % dimension fenêtre input
  largeur1 =round(large/2)-lebord1-bordure-largfen; % largeur description
  letexte =[largeur1 epais];                   % dimension description
  adroite =0;
  tipoint ={'-----'};
  lapos =positionfen('g','t',largreel,haut);
  lafig =figure('Name','TEXTE', 'tag','LireTexte', 'Position',lapos, ...
        'DefaultUIControlBackgroundColor',[0.8 0.8 0.8],...
        'defaultUIControlunits','pixels',...
        'defaultUIControlFontSize',11,...
      	'Resize','off', 'CloseRequestFcn',@Ppa.Fermeture);
  Ppa.Fig =lafig;
  haut =haut-35;
  largeur =large-(2*lebord1);
  uicontrol('Parent',lafig, 'HorizontalAlignment','Center', ...
        'Position',[lebord1 haut largeur epais], 'FontSize',13,...
        'Style','text', 'String','Choix du/des fichier(s) Texte(s)');
  haut =haut - 30; part3 =haut;
  largeur =large-bouton-(2*lebord1); Llarg =round(largeur/5);largeur =largeur-Llarg;
  uicontrol('Parent',lafig, 'tag','NomdeFichier', 'BackgroundColor',[1 1 1], ...
           'FontSize',10, 'HorizontalAlignment','Left', 'Style','edit', ...
           'Position',[lebord1 haut largeur epais], 'Callback',@Ppa.Fichiermanuel);
  uicontrol('Parent',lafig, 'tag','MultiFichier', 'FontSize',10, ...
           'BackgroundColor',[1 1 1], 'Position',[lebord1+largeur haut Llarg epais], ...
           'HorizontalAlignment','Right', 'Style','popupmenu','string',tipoint);
  largeur =lebord1+largeur+Llarg;
  uicontrol('Parent',lafig, 'Callback',@Ppa.Selection, ...
	          'Position',[largeur haut-1 bouton epais], 'String','...');
  haut =haut-15;
  largeur =large-(2*lebord1);
  uicontrol('Parent',lafig, 'Position',[lebord1 haut largeur ptitepais], ...
            'HorizontalAlignment','Left', 'FontSize',7, 'Style','text',...
            'String','Inscrire le PATH au complet');
  haut =haut-5;
  posx =lebord3; posy =part3;
  uicontrol('Parent',lafig, 'tag','toggleModEss', 'position',[posx posy 3*bouton epais],...
            'TooltipString','Si plusieurs essais par fichier, ils sont les uns au dessus des autres', ...
            'style','togglebutton','value',0, 'callback',@Ppa.ToggleEssai, 'string','ESS :', 'Enable','off');
  % ****************on étale de gauche à droite
  if adroite
    lebord = lebord2;
    adroite=0;
  else
    lebord = lebord1;
    haut = haut - 35;
    adroite=1;
  end
  uicontrol('Parent',lafig, 'HorizontalAlignment','Right', ...
            'Position',[lebord haut letexte], 'Style','text',...
            'String','Nbres de canaux (colonnes): ');
  uicontrol('Parent',lafig,'tag','NumerodeCanales', 'BackgroundColor',[1 1 1], 'FontSize',10, ...
            'TooltipString','Nombre de canaux par essai', 'HorizontalAlignment','Center', ...
            'Position',[largeur1+lebord haut fenetre], 'Style','edit', 'String','1');
  if adroite
    lebord =lebord2;
    adroite =0;
  else
    lebord =lebord1;
    haut =haut - 35;
    adroite =1;
  end
  uicontrol('Parent',lafig, ...
        'Position',[lebord haut letexte], ...
        'HorizontalAlignment','Right', ...
        'Style','text',...
        'String','Nbre d''essai par fichier: ');
  uicontrol('Parent',lafig,'tag','NombreEssFich', ...     % Nbres d'essais/fichier
        'BackgroundColor',[1 1 1], ...
        'FontSize',10, ...
        'HorizontalAlignment','Center', ...
        'Position',[largeur1+lebord haut fenetre], ...
        'Style','edit', ...
        'String','1');
  if adroite
    lebord =lebord2;
    adroite =0;
  else
    lebord =lebord1;
    haut =haut - 35;
    adroite =1;
  end
  uicontrol('Parent',lafig, ...
        'Position',[lebord haut letexte], ...
        'HorizontalAlignment','Right', ...
        'Style','text',...
        'String','Nbre de lignes par essai: ');
  uicontrol('Parent',lafig,'tag','NombredeLignes', ...     % Nbres de lignes/essai
        'BackgroundColor',[1 1 1], ...
        'FontSize',10, ...
        'HorizontalAlignment','Center', ...
        'Position',[largeur1+lebord haut fenetre], ...
        'TooltipString','facultatif si un seul essai par fichier',...
        'Style','edit', ...
        'String','0');
  if adroite
    lebord = lebord2;
    adroite=0;
  else
    lebord = lebord1;
    haut = haut - 35;
    adroite=1;
  end
  uicontrol('Parent',lafig, ...
        'HorizontalAlignment','Right', ...
        'Position',[lebord haut letexte], ...
        'Style','text',...
        'String','Nb de lignes d''entête au début: ');
  uicontrol('Parent',lafig,'tag','NbdeLigneEntete', ...   % Nbre de ligne d'entête au début
        'BackgroundColor',[1 1 1], ...
        'FontSize',10, ...
        'HorizontalAlignment','Center', ...
        'Position',[largeur1+lebord haut fenetre], ...
        'TooltipString','Nb de lignes à sauter pour le premier essai au début du fichier',...
        'Style','edit', ...
        'String','0');
  if adroite
    lebord = lebord2;
    adroite=0;
  else
    lebord = lebord1;
    haut = haut - 35;
    adroite=1;
  end
  uicontrol('Parent',lafig, ...
        'HorizontalAlignment','Right', ...
        'Position',[lebord haut letexte], ...
        'Style','text',...
        'String','Fréquence d''échantillonage: ');
  uicontrol('Parent',lafig,'tag','ElFrecuencia', ...   % Fréquence 
        'BackgroundColor',[1 1 1], ...
        'FontSize',10, ...
        'HorizontalAlignment','Center', ...
        'Position',[largeur1+lebord haut fenetre], ...
        'Style','edit', ...
        'String','100');
  if adroite
    lebord = lebord2;
    adroite=0;
  else
    lebord = lebord1;
    haut = haut - 35;
    adroite=1;
  end
  uicontrol('Parent',lafig, ...
        'HorizontalAlignment','Right', ...
        'Position',[lebord haut letexte], ...
        'Style','text',...
        'String','Secondes coupées au début: ');
  uicontrol('Parent',lafig,'tag','ElCorte', ...    % Frontcut
        'BackgroundColor',[1 1 1], ...
        'FontSize',10, ...
        'HorizontalAlignment','Center', ...
        'Position',[largeur1+lebord haut fenetre], ...
        'Style','edit', ...
        'String','0');
  if adroite
    lebord = lebord2;
    adroite=0;
  else
    lebord = lebord1;
    haut = haut - 35;
    adroite=1;
  end
  letype=strcat('virgule','|','point virgule','|','espace','|','Tab');
  uicontrol('Parent',lafig, ...
        'Position',[lebord haut largeur1-25 epais], ...
        'HorizontalAlignment','Right', ...
        'Style','text',...
        'String','Délimiteur utilisé: ');
  uicontrol('Parent',lafig, 'tag','ElDelimitador',...     % Délimiteur
        'BackgroundColor',[1 1 1], 'FontSize',9, ...
        'Position',[largeur1+lebord-25 haut largfen+25 epais], ...
        'String',letype, ...
        'Style','popupmenu', ...
        'Value',1);
  if adroite
    lebord = lebord2;
    adroite=0;
  else
    lebord = lebord1;
    haut = haut - 35;
    adroite=1;
  end
  uicontrol('Parent',lafig, ...
        'Position',[lebord haut letexte], ...
        'HorizontalAlignment','Right', ...
        'Style','text',...
        'String','No. ligne des noms de canaux: ');
  uicontrol('Parent',lafig,'tag','ElLineaNombre', ...    % No ligne nom canaux
        'BackgroundColor',[1 1 1],'FontSize',10, ...
        'TooltipString','S''applique uniquement si il y a des lignes d''entête au début',...
        'HorizontalAlignment','Center', ...
        'Position',[largeur1+lebord haut fenetre], ...
        'Style','edit', ...
        'String','0');
  if adroite
    lebord = lebord2;
    adroite=0;
  else
    lebord = lebord1;
    haut = haut - 35;
    adroite=1;
  end
  uicontrol('Parent',lafig, 'tag','TexteNbdeLigneEnteteEss',...
        'HorizontalAlignment','Right', ...
        'Position',[lebord haut letexte], ...
        'Style','text',...
        'String','Nb de lignes d''entête par essai: ');
  uicontrol('Parent',lafig,'tag','NbdeLigneEnteteEss', ...   % Nbre de ligne d'entête par essai
        'BackgroundColor',[1 1 1], ...
        'FontSize',10, ...
        'HorizontalAlignment','Center', ...
        'Position',[largeur1+lebord haut fenetre], ...
        'TooltipString','S''applique uniquement si plusieurs essais par fichier (ne sera pas additionné à l''entête du début)',...
        'Style','edit', ...
        'String','0');
  lfen =largreel-posx-bordure;
  picty =haut-epais;
  uicontrol('Parent',lafig, ...
        'Position',[lebord haut letexte], ...
        'HorizontalAlignment','Right','visible','off', ...
        'Style','text','tag','primerotext',...
        'String','No d''échantillon 1ère colonne: ');
  uicontrol('Parent',lafig, ...    % No échantillon à la première colonne
        'BackgroundColor',[1 1 1], 'visible','off',...
        'Position',[largeur1+lebord haut fenetre], ...
        'Style','togglebutton','tag','elprimero', ...
        'TooltipString','Si la première colonne n''est pas répété et qu''elle contient le numéro d''échantillon',...
        'value',0,'string','Non', 'Callback',@Ppa.ToggleColon);
% ***********Fin des fenêtres d'édition
  haut = haut-60; largeur=100;posx=floor((large-largeur)/2);
  uicontrol('Parent',lafig, 'Callback',@Ppa.Lecture, ...     % Au Travail
	          'FontSize',11, 'Position',[posx haut largeur epais], 'String','Au Travail');
  exemple ={'Ligne d''entête';'Essai 1';'C1 C2 C3';' 1  2  3';' 4  5  6';' 7  8  9';...
            'Essai 2';'11 12 13';'14 15 16';'17 18 19';...
            'Essai 3';'21 22 23';'24 25 26';'27 28 29';'  ';'Etc...'};
  hfen =posy-haut-5;posy =haut;
  uicontrol('Parent',lafig,'tag','textefenverti',...
            'position',[lebord3 posy lfen hfen],...
            'FontName','FixedWidth',...
            'HorizontalAlignment','left','FontSize',9,...
            'style','text','string',exemple);
  lfen =280; hfen =90; posx =largreel-bordure-lfen; posy =bordure;
  exemple ={'Ligne d''entête';
            'Essai 1     Essai 2     Essai 3  E..';...
            'C1 C2 C3    C1 C2 C3    C1 C2 C3 C..';...
            ' 1  2  3    11 12 13    21 22 23 ...';...
            ' 4  5  6    14 15 16    24 25 26 ...';...
            ' 7  8  9    17 18 19    27 28 29 ...';'  '};
  uicontrol('Parent',lafig,'tag','textefenhoriz', 'FontName','FixedWidth', ...
            'position',[posx posy lfen hfen],'visible','off', 'style','text', ...
            'HorizontalAlignment','left','FontSize',9, 'string',exemple);
  set(lafig,'WindowStyle','modal');
end