%
% Interface graphique pour la classe CMoyAutourPt
%
% dont le but est de faire la moyenne entre deux échantillons
% ou autour d'un échantillon (point marqué) et d'inscrire le
% résultat dans un fichier texte.
%
function varargout = GuiMoyAutourPt(Ppa)

    % appel les menus multi-lingues
    hL =CGuiMLMoyPenteTrie();

    % création de la figure
    Lfen=450; Hfen=450;
    lapos =positionfen('G', 'H', Lfen, Hfen);
    fig =figure('Name', hL.name1, ...
            'Position',lapos, 'CloseRequestFcn',@Ppa.fermer,...
            'DefaultUIControlBackgroundColor',[0.8 0.8 0.8],...
            'DefaultUIControlunits','pixels',...
            'DefaultUIControlFontSize',10,...
            'Resize', 'off');

    % titre pour le choix des canaux
    mx=25; mxtext=mx; posx=mxtext; large=round((Lfen-2*mxtext)/2); largstd=125; ddy=10; dy=2*ddy; posy=Hfen-45; Htext=22; haut=Htext;
    uicontrol('Parent',fig, 'FontWeight','bold',...
            'Position',[posx posy large haut], ...
            'String',hL.selcan, ...
            'Style','text');

    % titre pour le choix des essais
    uicontrol('Parent',fig, 'FontWeight','bold',...
            'Position',[posx+large posy large haut], ...
            'String',hL.seless, ...
            'Style','text');

    % listbox pour le choix des canaux
    if Ppa.vg.nad>2;letop =Ppa.vg.nad;else letop =Ppa.vg.nad + 1;end
    haut=100; posy=posy-haut;
    uicontrol('Parent',fig, 'Tag','LBchoixCan', ...
            'BackgroundColor',[1 1 1], 'Style','listbox', ...
            'Position',[posx posy large haut], ...
            'String',Ppa.hdchnl.Listadname, ...
            'Min',1, 'Max',letop, 'Value',1);

    % listbox pour le choix des essais
    if Ppa.vg.ess>2;lemax =Ppa.vg.ess;else lemax =Ppa.vg.ess + 1;end
    uicontrol('Parent',fig, 'Tag','LBchoixEss', ...
            'BackgroundColor',[1 1 1], 'Style','listbox', ...
            'Position',[posx+large posy large haut], ...
            'String',Ppa.vg.lesess, ...
            'Min',1, 'Max',lemax, 'Value',1);

    % checkbox pour le choix des essais
    haut=Htext; posy=posy-haut;
    uicontrol('Parent',fig, 'Tag','CBchoixEss', ...
            'Position',[posx+large posy large haut], ...
            'String',hL.toutess, 'Style','checkbox', ...
            'Value',0, 'Callback',@Ppa.tous);

    % titre "séparateurs"
    large=largstd; posy =posy-haut-dy;
    uicontrol('Parent',fig, 'FontWeight','bold',...
            'Position',[posx posy large haut], ...
            'String',hL.lesep, 'Style','text');

    % popupmenu pour le choix du "séparateur"
    uicontrol('Parent',fig, 'Tag','PMchoixSep', 'FontSize',11, ...
            'Position',[posx posy-haut large haut], ...
            'String',hL.selsep, 'Style','popupmenu', 'Value',1);

    % titre fenêtre de travail
    large=largstd+2*mx; posx=posx+large;
    uicontrol('Parent',fig, 'FontWeight','bold',...
            'Position',[posx posy large haut], ...
            'String',hL.fentrav, 'Style','text');

    % fenêtre de travail (début)
    posx=posx+round(large/2); large=round(large/3); posx=posx-large; posy=posy-haut;
    uicontrol('Parent',fig, 'Tag','EDfenTravDebut', 'FontSize',11,...
            'Position',[posx posy large haut], 'String','p0', 'Style','edit', ...
            'TooltipString',hL.fentravtip1);

    % fenêtre de travail (fin)
    uicontrol('Parent',fig, 'Tag','EDfenTravFin', 'FontSize',11,...
            'Position',[posx+large posy large haut], 'String','pf', 'Style','edit', ...
            'TooltipString',hL.fentravtip1);

    % checkbox pour le choix "Autour des points"
    posy=posy-haut-dy-ddy; posx=mx; large=largstd;
    uicontrol('Parent',fig, 'Tag','CBchoixAutour', 'Style','checkbox', ...
            'Position',[posx posy large haut], 'String',hL.autpts, ...
            'Value',0, 'Callback',@Ppa.moyenneAutour);

    % nombre d'échantillon ou de secondes à garder avant et après
    posx=mx+large+2*mx; large=large-50;
    uicontrol('Parent',fig, 'Tag','EDnombreAvantApres', 'FontSize',11,...
            'Position',[posx posy large haut], 'String','10', 'Style','edit', ...
            'TooltipString',hL.autpttip, 'Visible','off');

    % type d'unité, échantillon ou seconde
    posx =posx+large; large=large+50;
    uicontrol('Parent',fig, 'Tag','PMchoixUnit', 'FontSize',11, ...
            'Position',[posx posy large haut], 'Style','popupmenu', ...
            'String',hL.tipunit, 'Value',1, 'Visible','off');

    % bouton au travail
    large=85; posx=round((Lfen-large)/2); haut=Htext; posy=posy-haut-2*dy;
    uicontrol('Parent',fig, 'Callback',@Ppa.travail, ...
            'Position',[posx posy large haut], 'String',hL.maw);

    % info sommaire au bas de la fenêtre
    posy=posy-haut-dy;
    uicontrol('Parent',fig, 'FontWeight','bold', 'Position',[0 posy Lfen haut], 'Style','text', ...
            'String','-------------------------------------------------------------------------------------');
    posx=mx; large=Lfen-2*posx; haut=2*Htext; posy=posy-haut-5;
    uicontrol('Parent',fig, 'FontSize',9, 'Position',[posx posy large haut], 'Style','text', ...
              'String',hL.info1);

    set(fig,'WindowStyle','modal');

    if nargout
    	% si la fonction père demande un retour, on lui envoie 'fig'
    	varargout{1} =fig;
    end

end
