%
% ***INTERFACE (GUI) POUR LE CALCUL DES STAT SUR LE COP***
%
% À revoir: La fonction de matlab "uitab", qui permet la gestion des onglet
%           je l'ai essayé en janv 2015 et j'aimais mieux la mienne.
%
% EN ENTRÉE  Ppa  --> un objet de la classe  CGuiStat4COP
%
function fig =GuiStat4COP(Ppa)
  hA =CAnalyse.getInstance();
  Ofich =hA.findcurfich();
  hdchnl =Ofich.Hdchnl;
  vg =Ofich.Vg;
  largeur =500; hauteur =450;
  posfig =positionfen('G','C',largeur,hauteur,hA.OFig.fig);
  fig =figure('Name', 'Stat 4 COP', 'Position',posfig, 'Resize', 'off', ...				
          'CloseRequestFcn',@Ppa.terminus, 'DefaultUIControlBackgroundColor',Ppa.couleurRef, ...
          'DefaultUIPanelBackgroundColor',Ppa.couleurRef, 'DefaultUIControlUnits','pixels', ...
          'DefaultUIPanelUnits','pixels', 'DefaultUIControlFontUnits','pixels', ...
          'DefaultUIControlFontSize',12, 'DefaultUIPanelTitlePosition','rightbottom', ...
          'DefaultUIControlFontName','MS Sans Serif', 'DefaultUITableFontName','FixedWidth');
  hbout =25; bordure =2*hbout; dx =15; dy =20; dy2 =dy-5; dy3 =dy2-5; lbout =100;
  %------------------
  % Panel des onglets
  lpan =largeur; hpan =hbout; posx =0; posy =hauteur-hpan; ppan =[posx posy lpan hpan];
  pan =uipanel('Parent',fig, 'Tag','PanelOnglet', 'title','', 'Position',ppan, 'BackgroundColor',Ppa.couleurRef);
      %--------------
      % onglet Canaux
      letit ='Canaux'; posx =0; posy =0; large =length(letit')*6+30; haut =hpan-2;
      o1 =uicontrol('Parent',pan, 'Tag','BoutonOnglet', 'Position',[posx posy large haut], 'String',letit, ...
                    'Callback',@Ppa.showPanel, 'BackgroundColor',Ppa.couleurPan);
      %------------------
      % onglet Facultatif
      letit ='Facultatif'; posx =posx+large-1; large =length(letit')*6+30;
      o2 =uicontrol('Parent',pan, 'Tag','BoutonOnglet', 'Position',[posx posy large haut], 'String',letit, ...
                    'Callback',@Ppa.showPanel);
      %-------------
      % onglet Autre
      letit ='Un poco mas lejos'; posx =posx+large-1; large =length(letit')*6+30;
      o3 =uicontrol('Parent',pan, 'Tag','BoutonOnglet', 'Position',[posx posy large haut], 'String',letit, ...
                    'TooltipString','Un peu plus loin...', 'Callback',@Ppa.showPanel);
  posx =2; lpan =largeur-2*posx+1; posy =2*bordure; hpan =hauteur-posy-ppan(4); posPan =[posx posy lpan hpan];
  %-------------
  % Panel Canaux
  pan =uipanel('Parent',fig, 'Tag','PanelCanaux', 'title','Canaux', 'Position',posPan, 'BorderType','beveledin');
    set(o1, 'Userdata',pan);
    Ppa.setCurPan(pan); posy =hpan;
    %-----------------
    % CHOIX DES CANAUX
    lesCanaux ={'aucun...'};
    lesCanaux(2:length(hdchnl.Listadname)+1) =hdchnl.Listadname;
    posx =dx; large =lpan-2*posx; haut =hbout; posy =posy-haut-dy-dy2;
    uicontrol('Parent',pan, 'FontWeight','bold', 'Position',[posx posy large haut],...
              'HorizontalAlignment','center', 'String','Choix des canaux', 'Style','text');
    set(pan, 'DefaultUIControlFontSize', 11);
    %---
    % Cpx
    posx =1; largeText =90; largeBox =lpan-2*largeText-posx; posy =posy-haut-dy2;
    uicontrol('Parent',pan, 'Style','text', 'position',[posx posy+1 largeText haut-2], ...
              'FontWeight','bold', 'String','Cpx:  ', 'HorizontalAlignment','right');
    cualCanal =(Ppa.getCanCpx <= vg.nad)*Ppa.getCanCpx+1;
    uicontrol('Parent',pan, 'Style','popupmenu', 'Tag','CanauxCpx', 'Position',[posx+largeText posy largeBox haut], ...
              'FontSize',10, 'String',lesCanaux, 'Value',cualCanal, 'Callback',@Ppa.changeCanCpx);
    %---
    % Cpy
    posy =posy-haut-dy3;
    uicontrol('Parent',pan, 'Style','text', 'position',[posx posy+1 largeText haut-2], ...
              'FontWeight','bold', 'String','Cpy:  ', 'HorizontalAlignment','right');
    cualCanal =(Ppa.getCanCpy <= vg.nad)*Ppa.getCanCpy+1;
    uicontrol('Parent',pan, 'Style','popupmenu', 'Tag','CanauxCPy', 'Position',[posx+largeText posy largeBox haut], ...
              'FontSize',10, 'String',lesCanaux, 'Value',cualCanal, 'Callback',@Ppa.changeCanCpy);
    %-----------------
    % Borne de travail
    posy =posy-haut-2*dy2;
    lesBornes =strtrim(Ppa.getBornesText());
    uicontrol('Parent',pan, 'Style','text', 'position',[posx posy+1 largeText haut-2], ...
              'FontWeight','bold', 'String','Borne(s):  ', 'HorizontalAlignment','right');
    uicontrol('Parent',pan, 'Style','edit', 'Position',[posx+largeText posy largeBox haut], ...
              'FontSize',10, 'String',lesBornes, 'Tag','BorneDeTravail', ...
              'TooltipString','/5 10 10 15/i Début incrément overlap Fin/Laissez vide pour ne pas avoir de résultat par tranche temporelle');
   %__________________
   % Fichier de sortie
    posx =25; large2 =20; large =lpan-2*posx-large2; posy =posy-haut-2*dy; hautTop =haut-15;
    uicontrol('Parent',pan, 'Style','text', 'position',[posx posy+haut large hautTop], ...
              'FontSize',8, 'String','Fichier de sortie', 'HorizontalAlignment','left');
    uicontrol('Parent',pan, 'Style','edit', 'Tag','FichierSortie', 'Position',[posx posy large haut], ...
              'FontSize',10, 'String',Ppa.getFichierSortie(), ...
              'TooltipString','Entrez un nom de fichier pour l''écriture des résultats');
    uicontrol('Parent',pan, 'position',[posx+large posy large2 haut], 'FontSize',12, 'String','...', ...
              'FontWeight','bold', 'HorizontalAlignment','center', 'Callback',@Ppa.changeFichierSortie);
  %_________________
  % Panel facultatif
  pan =uipanel('Parent',fig, 'Tag','PanelFacultatif', 'title','Facultatif', 'Position',posPan, ...
               'TitlePosition','rightbottom', 'BorderType','beveledin', 'Visible','off');
  set(o2, 'Userdata',pan);
    %________________
    % Numéro du sujet
    posx =largeText; posy =hpan-haut-3*dy;
    uicontrol('Parent',pan, 'Style','text', 'position',[posx posy+1 2*largeText haut-2], ...
              'FontWeight','bold', 'String','Numéro du sujet:  ', 'HorizontalAlignment','right');
    uicontrol('Parent',pan, 'Style','edit', 'Tag','NumeroSujet', 'Position',[posx+2*largeText posy largeText haut], ...
              'FontSize',10, 'String',Ppa.getNumeroSujet());
    %----------------------------------------
    % Plage pour moyenner la valeur du rebase
    posy =posy-haut-2*dy2;
    onRecup =Ppa.getRecup();
    if onRecup
      onMontre ='on';
    else
      onMontre ='off';
    end
    uicontrol('Parent',pan, 'Style','radiobutton', 'position',[posx posy+1 largeText haut-2], ...
              'FontWeight','bold', 'String','Recup?  ', 'Value',onRecup, 'CallBack',@Ppa.changeRecup, ...
              'TooltipString','sert à faire une sorte de "rebase" pour certains paramètres');
    uicontrol('Parent',pan, 'Style','text', 'position',[posx+largeText posy+haut largeText hautTop], ...
              'FontSize',8, 'String','Début', 'HorizontalAlignment','center');
    uicontrol('Parent',pan, 'Style','edit', 'Tag','RecupDebut', 'Position',[posx+largeText posy largeText haut], ...
              'FontSize',10, 'String',Ppa.getRecupDebutText(), 'Enable',onMontre, ...
              'TooltipString','Valeur de début (en sec) considéré comme au repos');
    uicontrol('Parent',pan, 'Style','text', 'position',[posx+2*largeText posy+haut largeText hautTop], ...
              'FontSize',8, 'String','Fin', 'HorizontalAlignment','center');
    uicontrol('Parent',pan, 'Style','edit', 'Tag','RecupFin', 'Position',[posx+2*largeText posy largeText haut], ...
              'FontSize',10, 'String',Ppa.getRecupFinText(), 'Enable',onMontre, ...
              'TooltipString','Valeur de fin (en sec) considéré comme au repos');
    %-------
    % Filtre
    posy =posy-haut-2*dy2;
    onFiltre =Ppa.getOnFiltre();
    if onFiltre
      onMontre ='on';
    else
      onMontre ='off';
    end
    uicontrol('Parent',pan, 'Style','radiobutton', 'position',[posx posy+1 largeText haut-2], ...
              'FontWeight','bold', 'String','Filtre?  ', 'Value',onFiltre, 'CallBack',@Ppa.changeFiltre, ...
              'TooltipString','Les valeurs de fréquences de coupure et ordre sont celles par défauts');
    uicontrol('Parent',pan, 'Style','text', 'position',[posx+largeText posy+haut largeText hautTop], ...
              'FontSize',8, 'String','Fréq. coupure', 'HorizontalAlignment','center');
    uicontrol('Parent',pan, 'Style','edit', 'Tag','FrequenceDeCoupure', 'Position',[posx+largeText posy largeText haut], ...
              'FontSize',10, 'String',num2str(Ppa.getFreqCoupure()), 'Enable',onMontre, ...
              'TooltipString','doit être inférieure à la fréquence d''acquisition divisé par 2');
    uicontrol('Parent',pan, 'Style','text', 'position',[posx+2*largeText posy+haut largeText hautTop], ...
              'FontSize',8, 'String','ordre du filtre', 'HorizontalAlignment','center');
    uicontrol('Parent',pan, 'Style','edit', 'Tag','OrdreDuFiltre', 'Position',[posx+2*largeText posy largeText haut], ...
              'FontSize',10, 'String',num2str(Ppa.getOrdreFiltre()), 'Enable',onMontre);
    %_______________
    % Fenêtre Differ
    posy =posy-haut-2*dy2;
    uicontrol('Parent',pan, 'Style','text', 'position',[posx posy+1 2*largeText haut-2], ...
              'FontWeight','bold', 'String','Fenêtre pour Differ:  ', 'HorizontalAlignment','right');
    uicontrol('Parent',pan, 'Style','edit', 'Tag','FenetreDiffer', 'Position',[posx+2*largeText posy largeText haut], ...
              'FontSize',10, 'String',num2str(Ppa.getFenetreDiffer()), ...
              'TooltipString','fenêtre coulissante pour le calcul de la vitesse avec Differ');
  %__________________
  % Panel un poco mas
  pan =uipanel('Parent',fig, 'Tag','PanelUnPocoMas', 'title','Un poco mas lejos', 'Position',posPan, ...
               'TitlePosition','rightbottom', 'BorderType','beveledin', 'Visible','off');
  set(o3, 'Userdata',pan);
    %_____
    % Aide
    leTexte =lireLeHelp();
    posx =25; large =lpan-2*posx; haut =hbout; posy =hpan-3*haut;
    uicontrol('Parent',pan, 'Position',[posx posy large haut], 'FontWeight','bold', ...
              'HorizontalAlignment','center', 'String','Stat - 4 - COP', 'Style','text');
    haut =posy-hbout; posy =posy-haut;
    uicontrol('Parent',pan, 'Position',[posx posy large haut], 'Max',15, 'Min',1, ...
              'HorizontalAlignment','left', 'String',leTexte, 'Style','edit', 'FontName','FixedWidth');
  %----------------
  % Panel du Status
  lpan =largeur; hpan =hbout; posx =0; posy =0;
  pan =uipanel('Parent',fig, 'Tag','PanelStatus', 'title','', 'Position',[posx posy lpan hpan], ...
               'BackgroundColor',Ppa.couleurPan, 'BorderType','beveledout');
      %-------
      % Status
      posx =dx; large =lpan-2*dx; haut =hpan;
      ss =uicontrol('Parent',pan, 'Style','text', 'position',[posx posy large haut], 'FontSize',14, ...
                    'BackgroundColor',Ppa.couleurPan, 'String','', 'FontWeight','bold', ...
                    'Tag','TextStatus', 'HorizontalAlignment','center');
      Ppa.afficheStatus();
  % AU TRAVAIL
  large =lbout; posx =round((lpan-large)/2); posy =2*haut;
  uicontrol('Parent',fig, 'Position',[posx posy large haut], 'Callback',@Ppa.auTravail, 'String','Au travail');
  set(fig,'WindowStyle','modal');
end

function t =lireLeHelp()
  t ={sprintf(['\nCette fonction exécute les mêmes calculs que la fonction stat4cop9.m ' ...
               'qui se trouve sur le serveur du grame. Elle effectue les calculs sur ' ...
               'plusieurs variables dépendantes permettant d''analyser la stabilité posturale.']); ...
      sprintf('\n_____________\n> PARAMÈTRES'); ...
      sprintf(['_______\n- Recup\nUtilisé pour calculer: COPsteady(max|min)(X|Y)\n' ...
               'Util si on veut la position du CP au moment ou la vitesse est Max|MIn, ' ...
               'et ce, par rapport à une valeur stationnaire. Pour avoir cette valeur stationnaire, '...
               'vous devez fournir une plage temporelle ou le sujet est au repos ' ...
               '(comme par exemple les premières secondes de l''expérience).' ...
               ' Une moyenne des données sera faite sur cette plage.\n']); ...
      sprintf(['_______\n- Borne\n' ...
               'Si les tranches temporelles ne sont pas également distribuées alors entrez le ' ...
               'début et la fin de chacune à la suite comme ceci:\n 5 10 10 15 45 50\n']); ...
      sprintf('Si laissé vide, il n''y a pas de calcul par tranche temporelle\n'); ...
      sprintf(['Par contre, si vos valeurs sont incrémentés de façon régulière, ' ...
               'commencez la ligne avec la lettre "i", pour incrémentable et utilisez ceci:\n\n' ...
               'i Début Fin Incrément Overlap\n']); ...
      sprintf(['Pour  "Début et Fin", la syntaxe habituelle est acceptée\n' ...
               '  Pi --> premier échantillon\n  Pf --> dernier échantillon\n' ...
               '  P1 --> premier point marqué, P2 le deuxième etc...\n' ...
               '   4 --> valeur numérique est un nombre de seconde\n']); ...
      sprintf('Incrément --> longueur de la plage temporelle (en sec)\n'); ...
      sprintf(['  Overlap --> valeur à ajouter si on veut croiser les plages (en sec),' ...
               ' peut être positif ou négatif\n']); ...
      sprintf(['Ex: soit une acquisition de 25 secondes\n\n' ...
      ' SYNTAXE       BORNES DE TRAVAIL            Nb de Plage\n\n' ...
      'i 4 Pf 5  0    4 9 9 14 14 19 19 24         4 plages\n' ...
      'i 4 Pf 5 -1    4 9 8 13 12 17 16 21 20 25   5 plages\n' ...
      'i 4 Pf 5 +1    4 9 10 15 16 21              3 plages\n']); ...
      sprintf(['_________\n- Vitesse\nPour le calcul de la vitesse, le programme differ.m est utilisé ' ...
               'avec une fenêtre de 11 par défaut\n\n']); ...
      sprintf('Initié par M. Simoneau, Janvier 2002\npuis...\nmodifié par plusieurs collaborateurs. \n')};
end