%
% INTERFACE (GUI) POUR LE TRAITEMENT DE CANAL
%
% EN ENTRÉE on a Papa -->  un objet de la classe CTretcan
%
function fig =GuiTretcan(Papa)
  OA =CAnalyse.getInstance();
  Ofich =Papa.fid;
  hdchnl =Ofich.Hdchnl;
  vg =Ofich.Vg;

  % on lit la structure contenant le texte à afficher selon le choix de la langue
  tt =CGuiMLTretcan();

  largeur =Papa.largeur; lebord1 =Papa.lebord1;
  if vg.ess > 2;top =vg.ess;else top =vg.ess+1;end
  intboutv =6; intbouth =8; lptbout =25; hptbout =27; lfr =2*lebord1+4*lptbout+3*intbouth;  % petits boutons
  xmax =2*lebord1+largeur+lebord1+2*lfr+1; ymax =495;
  lebord31 =2*lebord1+largeur; lebord32 =lebord31+lfr+1;
  lebordD =xmax+5;
  lgbout =80; lebord21 =round((xmax-lgbout)/2);haut =85;haut2 =135;
  espv =20; haut3 =2*espv+6*hptbout+5*intboutv;
  lapos =positionfen('G','B',xmax,ymax);
  fig =figure('Name',tt.name, 'Position',lapos, ...
              'CloseRequestFcn',@Papa.fermer,...
              'DefaultUIControlBackgroundColor',[0.8 0.8 0.8],...
              'defaultUIControlunits','pixels',...
              'defaultUIControlFontSize',9, 'Resize','off');
  % TITRE DE L'INTERFACE
  ypos =ymax-30;xpos =round((xmax-400)/2);
  uicontrol('Parent',fig, 'HorizontalAlignment','center', 'Position',[xpos ypos 400 25],...
            'FontSize',12, 'FontWeight','bold', 'Style','text', 'String',tt.title);
  % APPLIQUER À TOUS LES ESS
  ypos =ypos-40;xpos =lebord1; YG =ypos; Larg =round(largeur*1.15);
  uicontrol('Parent',fig, 'tag','CBess', 'Style','checkbox', ...
            'Callback',@Papa.affess, 'Position',[xpos ypos Larg 25], ...
            'String',tt.alltrial, 'Value',1);
  % GARDER LES POINTS
  xpos =2*lebord1+Larg;
  uicontrol('Parent',fig, 'tag','GarderPoints', 'Style','checkbox', ...
            'Callback',@Papa.GarderPoints, 'Position',[xpos ypos Larg 25], ...
            'TooltipString',tt.keeppttip, ...
            'String',tt.keeppt, 'Value',Papa.lespts);
  % CHOIX DES ESSAIS
  xpos =lebordD;
  uicontrol('Parent',fig, 'tag','LeTitess',...
            'HorizontalAlignment','center', 'Position',[xpos ypos largeur 20], ...
            'String',tt.seless, 'Style','text');
  ypos =ypos-haut2;
  uicontrol('Parent',fig, 'tag','LBess', 'BackgroundColor',[1 1 1], 'Style','listbox',...
            'Position',[xpos ypos largeur haut2], 'String',vg.lesess, ...
            'Min',1, 'Max',top, 'Value',1);
  % CATÉGORIES
  if vg.niveau & ~isempty(vg.lescats)
    ypos =ypos-50;
    uicontrol('Parent',fig, 'tag','LeTitcat',...
              'HorizontalAlignment','center', 'Position',[xpos ypos largeur 20], ...
              'String',tt.selcat, 'Style','text');
    ypos =ypos-haut2;
  	ttt =length(vg.lescats);
  	if ttt <= 2, ttt =ttt+1; end;
    uicontrol('Parent',fig, 'tag','LBcat', 'BackgroundColor',[1 1 1], ...
              'Position',[xpos ypos largeur haut2], 'Style','listbox', ...
              'Callback',@Papa.affess2, 'Min',1, 'Max',ttt, ...
              'String',vg.lescats, 'Value',1);
  else
    ypos =ypos-50-haut2;
  end
  % LIGNE DE COMANDE-SUPP-?
  yrepere =ypos;
  lahaut =30; ypos =ypos-lahaut; xpos =lebord1;large =xmax-(2*lebord1)-15-lptbout-intbouth;
  uicontrol('Parent',fig, 'tag','Elastring', 'BackgroundColor',[1 1 1], ...
            'Position',[xpos ypos large lahaut], 'FontSize',11, 'Style','edit', ...
            'String','', 'TooltipString',tt.ligcommtip);
  xpos =xpos+large; large =lptbout+intbouth;
  uicontrol('Parent',fig, 'FontSize',9,...
          'Callback','set(findobj(''tag'',''Elastring''),''string'','''')', ...
          'HorizontalAlignment','center', 'Position',[xpos ypos large 30], 'String',tt.delstr);
  xpos =xpos+large;
  uicontrol('Parent',fig, 'FontSize',12,...
          'Callback','web(''http://mouvement.kin.ulaval.ca/kinetu/index.php/Analyse#Traitement_de_canal'',''-browser'',''-new'')', ...
          'backgroundcolor',[1 1 0], 'HorizontalAlignment','center',...
          'Position',[xpos ypos 15 30], 'String','?');
  % CHOIX DES CANAUX
  yrepere =yrepere+50;
  ypos =yrepere+haut3;xpos =lebord1;
  uicontrol('Parent',fig, 'HorizontalAlignment','center',...
            'Position',[xpos ypos largeur 20], 'Style','text',...
            'String',tt.canal);
  ypos =yrepere;
  uicontrol('Parent',fig, 'tag','LBcan',...
            'BackgroundColor',[1 1 1], ...
            'Position',[xpos ypos largeur haut3], ...
            'String',hdchnl.Listadname, 'Callback',@Papa.affcan, ...
            'Style','listbox', 'Value',1);
  % CLAVIER NUMÉRIQUE
  xpos =lebord31;
  uicontrol('Parent',fig, 'HorizontalAlignment','center',...
            'Position',[xpos ypos+haut3 lfr 20], 'Style','text',...
            'String',tt.clavnum);
  uipanel('Parent',fig, 'units','pixels','Position',[xpos ypos lfr haut3],...
            'BackgroundColor',[0.9 0.9 0.9],'bordertype','beveledin');
  % CE QUI VA APPARAÎTRE SUR LES TOUCHES
  tuch1 ={'7','4','1','0','8','5','2','.','9','6','3','-',char(247),'x','-','+'};
  % CE QUI VA APPARAÎTRE SUR LA LIGNE DE COMMANDE
  tuch2 ={'7','4','1','0','8','5','2','.','9','6','3','-','/','*','-','+'};
  U =1; xpos =lebord31+lebord1;
  for s =1:3
    ypos =yrepere+haut3-hptbout-espv;
    for k =1:4
      uicontrol('Parent',fig, 'Callback',@Papa.latouche, ...
            'FontSize',10, 'HorizontalAlignment','center', 'FontWeight','bold',...
            'Position',[xpos ypos lptbout hptbout], 'String',tuch1{U}, 'UserData',tuch2{U});
      U =U+1;
      ypos =ypos-hptbout-intboutv;
    end
    xpos =xpos+lptbout+intbouth;
  end
  ypos =yrepere+haut3-hptbout-espv;
  for k =1:4
    uicontrol('Parent',fig, 'Callback',@Papa.latoucheplusvirg, ...
          'FontSize',10, 'HorizontalAlignment','center', 'FontWeight','bold',...
          'Position',[xpos ypos lptbout hptbout], 'String',tuch1{U}, 'UserData',tuch2{U},...
          'TooltipString',['C1,C2,' tuch2{U} tt.clavfnctip tuch1{U} ' C2']);
    U =U+1;
    ypos =ypos-hptbout-intboutv;
  end
  xpos =lebord31+lebord1; lbteg =lptbout; ypos =ypos-intboutv;
  uicontrol('Parent',fig, 'Callback',@Papa.latouche, ...
            'FontSize',10, 'HorizontalAlignment','center', 'FontWeight','bold',...
            'Position',[xpos ypos lbteg hptbout], 'String',',', 'UserData',',');
  xpos =xpos+lbteg+intbouth; lbteg =3*lptbout+2*intbouth;
  uicontrol('Parent',fig, 'Callback',@Papa.latouche, ...
            'FontSize',12, 'HorizontalAlignment','center', 'FontWeight','bold',...
            'Position',[xpos ypos lbteg hptbout], 'String','=,', 'UserData','=,');
  % CHOIX DES FONCTIONS
  xpos =lebord32; ypos =yrepere;
  uicontrol('Parent',fig, 'HorizontalAlignment','center',...
            'Position',[xpos ypos+haut3 lfr 20], ...
            'String',tt.fonction, 'Style','text');
  uipanel('Parent',fig, 'units','pixels','Position',[xpos ypos lfr haut3],...
            'BackgroundColor',[0.9 0.9 0.9],'bordertype','beveledin');
  xpos =xpos+lebord1;
  uicontrol('Parent',fig, 'tag','TraitInvFncTrig', 'Position',[xpos ypos-15 50 15], ...
            'String',tt.triginv, 'TooltipString',tt.triginvtip, 'Style','checkbox', 'Value',0);
  uicontrol('Parent',fig, 'tag','TraitCanDegre', 'Position',[xpos+55 ypos-15 75 15], ...
            'String',tt.deg, 'TooltipString',tt.degtip, 'Style','checkbox', 'Value',1);
  sss =tt.fnctlist;
  ssfix ={'pi','sin','cos','tan','diff','abs','dist1','dist2','dist3','long','csum','sqrt','exp'};
  % AFFICHAGE DE LA PREMIÈRE COLONNE
  ypos =yrepere+haut3-espv-hptbout;
  for U =1:6
    if (U == 1) | (U > 4)
      uicontrol('Parent',fig, 'tag','FoncMath', 'BackgroundColor',[1 1 1], ...
              'Position',[xpos ypos lptbout+intbouth hptbout], 'String',sss{U,1}, ...
              'UserData',ssfix{U}, 'TooltipString',sss{U,2}, 'Callback',@Papa.latoucheplusvirg);
    else
      uicontrol('Parent',fig, 'tag','FoncTrigo', 'BackgroundColor',[1 1 1], ...
              'Position',[xpos ypos lptbout+intbouth hptbout], 'String',sss{U,1}, ...
              'UserData',ssfix{U}, 'TooltipString',sss{U,2}, 'Callback',@Papa.affichfoncttrigo);
    end
    ypos =ypos-hptbout-intboutv;
  end
  % AFFICHAGE DE LA DEUXIÈME COLONNE (BOUTON LARGE)
  ypos =yrepere+haut3-espv-hptbout; xpos =xpos+lptbout+2*intbouth;
  for U =7:11
    uicontrol('Parent',fig, 'tag','FoncMath', 'BackgroundColor',[1 1 1], ...
            'Position',[xpos ypos 3*lptbout hptbout], 'String',sss{U}, ...
            'UserData',ssfix{U}, 'TooltipString',sss{U,2}, 'Callback',@Papa.latoucheplusvirg);
    ypos =ypos-hptbout-intboutv;
  end
  % RESTE À AFFICHER LA DERNIÈRE LIGNE (TOUJOURS DANS LA 2ième COLONNE)
  uicontrol('Parent',fig, 'tag','FoncMath', 'BackgroundColor',[1 1 1], ...
            'Position',[xpos ypos lptbout+intbouth hptbout], 'String',sss{12,1}, ...
            'UserData',ssfix{12}, 'TooltipString',sss{12,2}, 'Callback',@Papa.latoucheplusvirg);
  xpos =xpos+lptbout+2*intbouth;
  uicontrol('Parent',fig, 'tag','FoncMath', 'BackgroundColor',[1 1 1], ...
            'Position',[xpos ypos lptbout+intbouth hptbout], 'String',sss{13,1}, ...
            'UserData',ssfix{13}, 'TooltipString',sss{13,2}, 'Callback',@Papa.latoucheplusvirg);
  ypos =25;xpos =lebord21;
  uicontrol('Parent',fig, 'Callback',@Papa.autravail, ...
            'FontSize',12, 'HorizontalAlignment','center',...
            'Position',[xpos ypos lgbout 25], 'String',tt.buttonGo);
  Papa.hdr.rate =0;
  set(fig,'WindowStyle','modal');

end