%
% INTERFACE (GUI) POUR LE CHOIX DES CANAUX LORS DE L'AFFICHAGE EN MODE X-Y
%
% EN ENTRÉE on a  Papa --> un objet de la classe CModeXY
%
function fig =IModeXY(Papa)
  try
    set(findobj('Type','uicontrol','tag', 'IpAxeSlider'),'visible','off');
    OA =CAnalyse.getInstance();
    if isempty(OA.laPosXY)
      figIp =Papa.getFigIp();
      posfig =positionfen('G+','C',275,500,figIp);
      OA.laPosXY =posfig;
    else
      posfig =OA.laPosXY;
    end
    fig =figure('Name','MODE X-Y', 'tag','IpChoiXY',...
         'Resize','on','MenuBar','none', 'NumberTitle','off',...
         'Units','pixels','Position', posfig, 'Units','normalized',...
         'DoubleBuffer','on', 'visible','off',...
         'CloseRequestFcn','appelXY(''mnucacher'')',...
         'DefaultUIControlBackgroundColor',[0.8 0.8 0.8],...
         'defaultUIControlunits','normalized',...
         'defaultUIControlFontSize',9);
    Papa.Fig =fig;
  
    % *****CANAUX CHOISIS POUR ABCISSE/ORDONNÉES
    vg =Papa.Fid.Vg;
    hdchnl =Papa.Fid.Hdchnl;
    %
    % Pour chaque couple de canaux XY on aura
    % canalX1 -- canalY1
    % canalXj -- canalYj
    % canalXn --         le dernier canalY (soit le canalYn) peut être vide
    %
    esp15 =0.15;espc =0.023;esp5 =0.05;esp10 =0.1;h1 =0.2;h2 =0.35;hautf =0.04;boutton =0.25;
    largef =0.15;larfen =0.85;large =larfen;posx =(1-large)/2;haut =h1;posy =1-0.06-haut;
    conmnu =uicontextmenu;
  
    elTexto ={'Parent';fig; 'BackgroundColor';[1 1 1]; 'Callback';'appelXY(''mnuvoircan'')'; ...
              'Position';[posx posy large haut]; 'Style';'listbox'; 'Max';1;...
              'String';'vide'; 'UIContextMenu'; conmnu; 'Value';1};
    Papa.canoXY =CListBox1(elTexto);
  
    % Définition des ContextMenus
    item =uimenu(conmnu, 'Label', 'Effacer les lignes sélectionnées', 'Callback', 'appelXY(''effacer'')');
    item =uimenu(conmnu, 'Label', 'Effacer Toutes les lignes', 'Callback', 'appelXY(''effaceles'')');
  
    posy =posy+haut;haut =hautf;
    uicontrol('Parent',fig, ...
          'Position',[posx posy large haut], ...
          'HorizontalAlignment','Center', ...
          'Style','text',...
          'String','Abcisse ---***--- Ordonnée');
  
    % *****SÉLECTION DES CANAUX
    posy =posy-h1-h2-espc;haut =h2;
    elTexto ={'Parent';fig; 'BackgroundColor';[1 1 1]; 'Callback';'appelXY(''editcan'')';...
              'Position';[posx posy large haut]; 'Style';'listbox'; ...
              'TooltipString';'Double-Cliquer une fois pour définir le canal en Abcisse; Recommencer pour le canal en Ordonnée';...
              'String';hdchnl.adname; 'Max';1; 'Value';1};
    Papa.cano =CListBox2(elTexto);
  
    % *******AFFICHAGE EN FONCTION DU TEMPS
    haut =hautf;posy =posy-haut-espc;
    uicontrol('Parent',fig, ...
          'Tag','IpFilTemps',...
          'Callback','appelXY(''togglefiltmp'')',...
          'string','Afficher en fonction du temps',...
          'Position',[posx posy large haut], ...
          'Style','checkbox', ...
          'TooltipString','Activer le mode Fil du temps',...
          'value',vg.filtp);
  
    if vg.filtp
      actif ='on';
    else
      actif ='off';
    end
  
    large =largef;posy =posy-haut-espc;
    uicontrol('Parent',fig, ...
          'BackgroundColor',[1 1 1], ...
          'Tag','FilTempsMin',...
          'Callback','appelXY(''edittemps'')',...
          'Position',[posx posy large haut], ...
          'Style','edit', 'enable',actif,...
          'TooltipString','Valeur minimale de la section temporelle à afficher',...
          'String',num2str(vg.filtpmin));
  
    uicontrol('Parent',fig, ...
          'BackgroundColor',[1 1 1], ...
          'Tag','FilTempsMax',...
          'Callback','appelXY(''edittemps'')',...
          'Position',[posx+larfen-largef posy large haut], ...
          'Style','edit', 'enable',actif,...
          'TooltipString','Valeur maximale de la section temporelle à afficher',...
          'String',num2str(vg.filtpmax));
  
    % Slider du Temps pour mode XY
    tmax =max(hdchnl.sweeptime(:));
    tmin =min(hdchnl.frontcut(:));
    posy =posy-haut;large =1-2*posx;
    uicontrol('Parent',fig, 'tag','IpAxeTemps', 'Callback','appelXY(''deroultemps'')', 'enable',actif, ...
              'Position',[posx posy large haut], 'SliderStep', [0.05 0.15], ...
              'max',tmax, 'min',tmin, 'value',tmin, 'Style','Slider');
  
    % *******PARAMÈTRES POUR MARQUAGE XY
    haut =hautf;posy =posy-haut-2*espc;large =larfen-largef;
    uicontrol('Parent',fig, 'Tag','IpMarkX',...
          'Callback','appelXY(''marklesx'')',...
          'string','Marquer en X, Écart type en Y +/-',...
          'Position',[posx posy large haut], ...
          'Style','checkbox', ...
          'TooltipString','La position du/des points marqués, sera p/r aux X',...
          'value',vg.xymarkx);
  
    uicontrol('Parent',fig, 'BackgroundColor',[1 1 1], 'Tag','IpMarkXEcart',...
          'Callback','appelXY(''marklesecart'')', 'Position',[posx+large posy largef haut], ...
          'Style','edit', 'String',num2str(vg.xymarkxecart), ...
          'TooltipString','D''après le curseur du marqueur, écart type en Y');
  
    posy =posy-haut-espc;
    ligrec =abs(vg.xymarkx-1);
    uicontrol('Parent',fig, 'Tag','IpMarkY', 'Callback','appelXY(''marklesy'')', 'Style','checkbox', ...
          'string','Marquer en Y, Écart type en X +/-', 'Position',[posx posy large haut], ...
          'TooltipString','La position du/des points marqués, sera p/r aux Y', 'value',ligrec);
  
    uicontrol('Parent',fig, 'BackgroundColor',[1 1 1], 'Tag','IpMarkYEcart',...
          'Callback','appelXY(''marklesecart'')', 'Position',[posx+large posy largef haut], ...
          'Style','edit', 'String',num2str(vg.xymarkyecart), ...
          'TooltipString','D''après le curseur du marqueur, écart type en X');
  catch moo;
    disp(moo.stack(1));
    rethrow(moo);
  end
end