%
% Interface (GUI) pour demander les infos relatives au découpage
%   - enlever du temps au début ou à la fin des canaux/essais
%
% MEK - juillet 2009
%       retravailler 1 nov 2011
%
% EN ENTRÉE on a obj --> un objet de la classe CWdecoup
%
function IWdecoup(obj)
  OA =CAnalyse.getInstance();
  Ofich =OA.findcurfich();
  hdchnl =Ofich.Hdchnl;
  vg =Ofich.Vg;
  if vg.nad > 2
  	letop =vg.nad;
  else
  	letop =vg.nad+1;
  end
  lapos =positionfen('G','H',675,350);
  lafig = figure('Name','MENU DÉCOUPE', 'tag','DecoupeLafig',...
        'Position',lapos, 'CloseRequestFcn',@obj.fermer,...
        'DefaultUIControlBackgroundColor',[0.8 0.8 0.8],...
        'defaultUIControlunits','normalized ',...
        'defaultUIControlFontSize',12, 'Resize','on');
  % fenêtre séparé en deux: 0.3 et 0.7
  % PARTIE DE GAUCHE
  margex =0.03;margey =0.05;htext =0.075;fengch =0.35;fendrt =1-fengch;
  posx =margex;haut =htext;posy =1-margey-haut;large =fengch-2*margex;
  uicontrol('Parent',lafig, 'tag','DecoupeTextCanalRef', 'Position',[posx posy large haut], ...
          'HorizontalAlignment','center', 'FontWeight','bold',...
          'Style','text', 'String','Canal de référence');
  haut =htext*0.7; posy =posy-haut; canref =1;
  uicontrol('Parent',lafig, 'tag','DecoupeCanalRef', 'FontSize',10, ...
          'callback',@obj.quelcan, ...
          'BackgroundColor',[1 1 1], 'Position',[posx posy large haut], ...
          'String',hdchnl.Listadname, 'Style','popupmenu', 'Value',canref);
  haut =htext; posy =posy-margey-2*haut;large =fengch-2.1*margex;
  uicontrol('Parent',lafig, 'Position',[posx posy large haut], ...
          'HorizontalAlignment','left', 'FontWeight','bold',...
          'Style','text', 'String','Choix des canaux');
  haut =margey;posx =posx+large; large=large/4; posx =posx-large/2;
  uicontrol('Parent',lafig, 'tag','DecoupeTouCan', 'Position',[posx posy large haut], ...
            'FontSize',9, 'HorizontalAlignment','left', 'String','Tous', ...
            'Style','checkbox', 'Value',0, 'Callback', @obj.toucan);
  posboxtou =[posx+4*margex posy large haut];
  posx =margex;haut =posy*0.85;posy =posy-haut;large =fengch-2*margex;
  posbox =[posx posy large haut];
  uicontrol('Parent',lafig, 'tag','DecoupeCanaux', 'FontSize',10, ...
          'BackgroundColor',[1 1 1], 'Position',posbox, ...
          'String',hdchnl.Listadname, ...
          'Min',1, 'Max',letop, 'Style','listbox', 'Value',1);
  haut =margey;posy =posy-haut;
  uicontrol('Parent',lafig, 'tag','DecoupeFrontcut',...
          'Position',[posx posy large haut], 'FontSize',9,...
          'TooltipString','En gardant le frontcut, vous garder l''ordre temporel d''origine',...
          'HorizontalAlignment','left',...
          'String','Cumuler le "Frontcut"', 'Style','checkbox', 'Value',0);
  % PARTIE DE DROITE
  posx =fengch+margex;haut =htext;posy =1-margey-haut;large =fendrt-2*margex;
  letype ={'Points marqués', 'À tous les T sec.', 'Nb. d''intervals fixes'};
  uicontrol('Parent',lafig, 'Position',[posx posy large haut], ...
          'HorizontalAlignment','center', 'FontWeight','bold',...
          'Style','text', 'String','Critères pour le découpage');
  posy =posy-margey-haut;
  uicontrol('Parent',lafig, 'tag','DecoupeQueFaire',...
          'Position',[posx posy large haut], 'enable','off',...
          'HorizontalAlignment','center', 'String',letype, ...
          'Callback',@obj.choix, 'Style','popupmenu', 'Value',1);
  % CHOIX 1-2-3
  uicontrol('Parent',lafig, 'tag','DecoupeTousPoints', ...
          'Position',posboxtou, ...
          'FontSize',9, 'HorizontalAlignment','left', 'String','Tous', ...
          'Style','checkbox', 'Value',0, 'Callback', @obj.toupts);
  posbox([1 3]) =posboxtou([1 3]);
  ppp ={'1'};
  for U =2:max(hdchnl.npoints(canref,:))
    ppp{end+1} =num2str(U);
  end
  uicontrol('Parent',lafig, 'tag','DecoupeLesPoints', 'FontSize',10, ...
          'BackgroundColor',[1 1 1], 'Position',posbox, ...
          'String',ppp, ...
          'Min',1, 'Max',letop, 'Style','listbox', 'Value',1);
  largec1 =large*0.35;large =largec1;posy =posy-margey-haut;retoury =posy;
  uicontrol('Parent',lafig, 'tag','DecoupeTextInterUtil', 'Position',[posx posy large haut], ...
          'HorizontalAlignment','center', 'Style','text', 'visible','off', 'String','Intervalle utile');
  posy =posy-haut-0.5*margey;large =large/2;
  uicontrol('Parent',lafig, 'tag','DecoupeTextDebut', 'Position',[posx posy large haut], ...
          'HorizontalAlignment','center', 'Style','text', 'String','début');
  uicontrol('Parent',lafig, 'tag','DecoupeTextFin',...
          'Position',[posx+large posy large haut], ...
          'HorizontalAlignment','center',...
          'visible','off', 'Style','text', 'String','fin');
  posy =posy-haut;
  uicontrol('Parent',lafig, 'tag','DecoupeDebut',...
          'TooltipString','(p0=premier échantillon, pf le dernier) (valeur numérique=temps en sec) ou bien p1, p2... pour un point déjà marqué',...
          'Position',[posx posy large haut], 'Style','edit', 'String','p0');
  uicontrol('Parent',lafig, 'tag','DecoupeFin',...
          'TooltipString','(p0=premier échantillon, pf le dernier) (valeur numérique=temps en sec) ou bien p1, p2... pour un point déjà marqué',...
          'Position',[posx+large posy large haut], ...
          'Style','edit', 'visible','off', 'String','pf');
  posx =posx+2*large+margex;large =fendrt-largec1-3*margex;posy =retoury;
  uicontrol('Parent',lafig, 'tag','DecoupeTextPrecise2',...
          'Position',[posx posy large*0.75 haut], ...
          'HorizontalAlignment','right', 'visible','off',...
          'Style','text', 'String','Marquer à tous les (sec):  ');
  uicontrol('Parent',lafig, 'tag','DecoupeTextPrecise3',...
          'Position',[posx posy large*0.75 haut], ...
          'HorizontalAlignment','right', 'visible','off',...
          'Style','text', 'String','Nombre d''intervalles:  ');
  uicontrol('Parent',lafig, 'tag','DecoupePrecise2',...
          'Position',[posx+(large*0.75) posy large*0.15 haut], ...
          'TooltipString','valeur numérique en sec',...
          'Style','edit', 'visible','off', 'String','1');
  uicontrol('Parent',lafig, 'tag','DecoupePrecise3',...
          'Position',[posx+(large*0.75) posy large*0.15 haut], ...
          'TooltipString','Indiquez le nombre d''intervalles voulus',...
          'Style','edit', 'visible','off','String','2');
  posy =posy-haut-margey;
  uicontrol('Parent',lafig, 'tag','DecoupeTextTemps',...
          'Position',[posx posy large haut], 'HorizontalAlignment','center',...
          'Style','text', 'String','Temps à garder (sec)');
  posy =posy-haut-margey;posx =posx+(large/2);large =large/4;posx =posx-large;
  uicontrol('Parent',lafig, 'tag','DecoupeTextAvant',...
          'Position',[posx posy large haut], ...
          'HorizontalAlignment','right', 'Style','text', 'String','Avant: ');
  uicontrol('Parent',lafig, 'tag','DecoupeAvant',...
          'Position',[posx+large posy large*0.75 haut], ...
          'Style','edit', 'String','1');
  posy =posy-haut;
  uicontrol('Parent',lafig, 'tag','DecoupeTextApres',...
          'Position',[posx posy large haut], ...
          'HorizontalAlignment','right', 'Style','text', 'String','Après: ');
  uicontrol('Parent',lafig, 'tag','DecoupeApres',...
          'Position',[posx+large posy large*0.75 haut], ...
          'Style','edit', 'String','1');
  posx =posx+0.25*large;large =large*1.65;posy =posy/3;
  uicontrol('Parent',lafig, 'Callback',@obj.travail, ...
          'Position',[posx posy large haut], 'String','Au travail');
  obj.elchoix();
  set(lafig,'WindowStyle','modal');
end
